<h2>Loading and preprocessing the data</h2>

<p>Download into &#39;dataset.zip&#39; / extract into &#39;activity.csv&#39;</p>

<pre><code class="r">fileurl &lt;- &quot;https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip&quot;
download.file(fileurl, destfile = &quot;dataset.zip&quot;, method = &quot;curl&quot;)
unzip(&quot;dataset.zip&quot;)
activity &lt;- read.csv(&quot;activity.csv&quot;)
</code></pre>

<p>Add a column to specify the day of the week</p>

<pre><code class="r">activity$day &lt;- weekdays(as.Date(activity$date))
</code></pre>

<h2>What is mean total number of steps taken per day?</h2>

<p>Get the total amount of steps for each day:</p>

<pre><code class="r">totalStepsByDay &lt;- aggregate(activity$steps, by=list(Category=activity$date), FUN=sum)
</code></pre>

<p>Histogram:</p>

<pre><code class="r">library(ggplot2)
qplot(date, steps, data=activity, stat=&quot;summary&quot;, fun.y=&quot;sum&quot;, geom=&quot;bar&quot;)
</code></pre>


<p><img src="https://raw.githubusercontent.com/Linz17/RepData_PeerAssessment1/master/activityTotalStepsByDay.png" alt="plot"/></p>

<p>Get the mean an median of steps by day:</p>

<pre><code class="r">summary(totalStepsByDay$x)
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##      41    8841   10760   10770   13290   21190       8
</code></pre>

<p>The <strong>mean</strong> total number of steps taken per day is <strong>10770</strong>
The <strong>median</strong> total number of steps taken per day is <strong>10760</strong></p>

<h2>What is the average daily activity pattern?</h2>

<p>Get the mean amount of steps for each interval:</p>

<pre><code class="r">totalStepsByInterval &lt;- aggregate(activity$steps, by=list(Category=activity$interval), FUN=mean, na.rm=TRUE)
</code></pre>

<p>Get the interval with the most steps</p>

<pre><code class="r">totalStepsByInterval[which.max(totalStepsByInterval$x),]
</code></pre>

<pre><code>##     Category        x
## 104      835 206.1698
</code></pre>

<p>The 5-minute interval, on average across all the days in the dataset, that contains the maximum number of steps is:
<strong>835</strong> with <strong>206.1698</strong> steps on average</p>

<p>Plot:</p>

<pre><code class="r">plot(meanStepsByInterval, type=&quot;l&quot;, xlab=&quot;Interval&quot;, ylab=&quot;Steps&quot;)
</code></pre>

<p><img src="https://raw.githubusercontent.com/Linz17/RepData_PeerAssessment1/master/meanStepsByInterval.png" alt="plot"/></p>

<h2>Imputing missing values</h2>

<p>Total number of missing values in the dataset: <strong>2304</strong></p>

<pre><code class="r">sum(is.na(activity$steps))
</code></pre>

<pre><code>## [1] 2304
</code></pre>

<p>New dataset, filling gaps using mean:</p>

<pre><code class="r">noNAactivity &lt;- activity
for (i in 1:17568) {
  if (is.na(noNAactivity$steps[i])== TRUE) {
    noNAactivity$steps[i] &lt;- round(meanStepsByInterval[meanStepsByInterval[,1] == noNAactivity$interval[i],2])
  }
}
</code></pre>

<p>Old dataset: Mean = 10770 // Median = 10760</p>

<pre><code class="r">summary(totalStepsByDay$x)
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##      41    8841   10760   10770   13290   21190       8
</code></pre>

<p>New dataset: Mean = 10770 // Median = 10760</p>

<pre><code class="r">summary(totalStepsByDayFILLED$x)
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##      41    8841   10760   10770   13290   21190       8
</code></pre>

<p>Histogram:</p>

<pre><code class="r">library(ggplot2)
qplot(date, steps, data=noNAactivity, stat=&quot;summary&quot;, fun.y=&quot;sum&quot;, geom=&quot;bar&quot;)
</code></pre>

<p><img src="https://raw.githubusercontent.com/Linz17/RepData_PeerAssessment1/master/noNAactivityTotalStepsByDay.png" alt="Plot"/></p>

<h2>Are there differences in activity patterns between weekdays and weekends?</h2>

<p>Subsetting into 2 datasets: weekdaysActivity and weekendActivity.</p>

<pre><code class="r">weekdaysActivity &lt;- noNAactivity[noNAactivity$day %in% c(&quot;Monday&quot;, &quot;Tuesday&quot;, &quot;Wednesday&quot;, &quot;Thursday&quot;, &quot;Friday&quot;),]
weekendActivity &lt;- noNAactivity[noNAactivity$day %in% c(&quot;Saturday&quot;, &quot;Sunday&quot;),]
meanStepsByIntervalWeekdays &lt;- aggregate(weekdaysActivity$steps, by=list(Category=weekdaysActivity$interval), FUN=mean, na.rm=TRUE)
meanStepsByIntervalWeekends &lt;- aggregate(weekendActivity$steps, by=list(Category=weekendActivity$interval), FUN=mean, na.rm=TRUE)
</code></pre>

<p>Plot:</p>

<pre><code class="r">par(mfcol = c(2,1))
with(meanStepsByIntervalWeekdays, {
  plot(meanStepsByIntervalWeekdays, type = &quot;l&quot;, xlab=&quot;Interval&quot;, ylab=&quot;Steps&quot;)
  plot(meanStepsByIntervalWeekends, type = &quot;l&quot;, xlab=&quot;Interval&quot;, ylab=&quot;Steps&quot;)
})
</code></pre>

<p><img src="https://raw.githubusercontent.com/Linz17/RepData_PeerAssessment1/master/diffWeekdayWeekend.png" alt="Plot"/></p>

